yaml
name:Update Menu

on:
  push:
    paths:
      - 'data/cardapio.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
      
    - name: Process CSV
      run: node scripts/process-csv.js
      
    - name: Generate QR Code
      run: node scripts/generate-qrcode.js
      
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html qrcode.png
        git commit -m "Update menu" || exit 0
        git push
